repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
-   repo: local
    hooks:
    - id: pytest-check
      name: pytest-check
      stages: [commit]
      types: [python]
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
# - repo: local
#   hooks:
#     - id: trufflehog
#       name: TruffleHog
#       description: Detect secrets in your data.
#       entry: bash -c 'docker run -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///jonas_asad --only-verified --fail'
#       language: system
#       stages: ["commit", "push"]
- repo: https://github.com/pypa/pip-audit
  rev: v2.4.4
  hooks:
  - id: pip-audit

#Semgrep instalation if you want to use the docker image,
#however, if a user does not have docker installed locally or just wants to use the python version
#below is better. However, I have not managed to get it to work.
# - repo: local
#   hooks:
#     - id: semgrep
#       name: Semgrep Docker
#       description: Detect secrets in your data.
#       entry: bash -c 'docker run -v "$(pwd):/src" -i --rm returntocorp/semgrep semgrep scan --json . --config=auto --output=semgrep_results.json'
#       language: system
#       stages: ["commit", "push"]


# - repo: https://github.com/returntocorp/semgrep
#   rev: "v0.100.0"
#   hooks:
#     - id: semgrep
#       name: Semgrep Python
#       types: [python]
#       exclude: "^cli/tests/.+$|^scripts/.+$|^cli/setup.py$"
#       args: ["--config", "https://semgrep.dev/p/python", "--error"]
